using Content.Shared.CCVar;
using Content.Shared._Starlight.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Prototypes;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MiscTab : Control
{
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public MiscTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Starlight-edit: themes/layout moved to UI tab.

        // Channel can be null in replays so.
        // ReSharper disable once ConditionalAccessQualifierIsNonNullableAccordingToAPIContract
        ShowOocPatronColor.Visible = _playerManager.LocalSession?.Channel?.UserData.PatronTier is { };

        // Starlight-edit: themes/layout moved to UI tab.

        Control.AddOptionCheckBox(CVars.DiscordEnabled, DiscordRich);
        Control.AddOptionCheckBox(CCVars.ShowOocPatronColor, ShowOocPatronColor);
        Control.AddOptionCheckBox(CCVars.LoocAboveHeadShow, ShowLoocAboveHeadCheckBox);
        Control.AddOptionCheckBox(CCVars.HudHeldItemShow, ShowHeldItemCheckBox);
        Control.AddOptionCheckBox(CCVars.CombatModeIndicatorsPointShow, ShowCombatModeIndicatorsCheckBox);
        Control.AddOptionCheckBox(CCVars.OpaqueStorageWindow, OpaqueStorageWindowCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatEnableFancyBubbles, FancySpeechBubblesCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatFancyNameBackground, FancyNameBackgroundsCheckBox);
        Control.AddOptionCheckBox(CCVars.StaticStorageUI, StaticStorageUI);
        // Starlight-start
        Control.AddOptionCheckBox(StarlightCCVars.AutoPunctuate, AutoPunctuate);
        Control.AddOptionCheckBox(StarlightCCVars.UIGlassTheme, GlassThemeCheckBox);
        Control.AddOptionSlider(StarlightCCVars.UIGlassTransparency, GlassAlphaSlider, 0, 100, (_, value) => $"{value}%");
        Control.AddOptionCheckBox(StarlightCCVars.UIGlassAccentEnabled, GlassAccentCheckBox);
        Control.AddOptionColorSlider(StarlightCCVars.UIGlassAccent, GlassAccentSlider);
        Control.AddOptionCheckBox(StarlightCCVars.WieldBeforeRack, WieldBeforeRack);
        Control.AddOptionCheckBox(StarlightCCVars.ForceTestersTab, ForceTestersTab);
        // Starlight-end

        // Daiquiri: sliders appear only when their checkbox is on.
        Control.Initialize();
        GlassAlphaSlider.Visible = GlassThemeCheckBox.Pressed;
        GlassAccentSlider.Visible = GlassAccentCheckBox.Pressed;
        GlassThemeCheckBox.OnToggled += args => GlassAlphaSlider.Visible = args.Pressed;
        GlassAccentCheckBox.OnToggled += args => GlassAccentSlider.Visible = args.Pressed;
    }
}
