using System;
using System.Linq;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class BookWriterUiFragment : BoxContainer
{
    public event Action<string, string, string, string, string, string, string, bool, List<string>>? OnSaveBook;
    public event Action<string>? OnDeleteBook;
    public event Action<string>? OnPrintBook;

    private List<BookWriterBookInfo> _books = new();
    private long _printCooldown;

    public void UpdateState(List<BookWriterBookInfo> books, long printCooldown = 0)
    {
        _books = books;
        _printCooldown = printCooldown;
        ShowList();
    }
    private int _readPage;
    private string _readId = "";
    private bool _draftsOnly;

    public BookWriterUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
    }

    private string _search = "";
    private string _genreFilter = "";
    private BoxContainer? _chrome;
    private BoxContainer? _content;
    private BoxContainer? _searchRow;

    private void EnsureChrome()
    {
        if (_chrome != null && _content != null)
            return;

        var searchRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 4,
        };
        var searchInput = new LineEdit
        {
            HorizontalExpand = true,
            PlaceHolder = Loc.GetString("book-writer-search-placeholder"),
            Text = _search,
        };
        searchInput.OnTextChanged += _ =>
        {
            _search = searchInput.Text;
            RefreshList();
        };
        var genrePick = new OptionButton();
        genrePick.AddItem(Loc.GetString("book-writer-genre-all"), 0);
        for (var i = 0; i < BookWriterCovers.Genres.Length; i++)
            genrePick.AddItem(Loc.GetString(BookWriterCovers.Genres[i].Loc), i + 1);
        genrePick.Select(string.IsNullOrEmpty(_genreFilter)
            ? 0
            : Array.FindIndex(BookWriterCovers.Genres, g => g.Value == _genreFilter) + 1);
        genrePick.OnItemSelected += args =>
        {
            _genreFilter = args.Id <= 0 ? "" : BookWriterCovers.Genres[args.Id - 1].Value;
            // Daiquiri: engine doesn't refresh the label on pick — do it manually.
            genrePick.Select(args.Id <= 0
                ? 0
                : Array.FindIndex(BookWriterCovers.Genres, g => g.Value == _genreFilter) + 1);
            RefreshList();
        };
        searchRow.AddChild(searchInput);
        searchRow.AddChild(genrePick);
        _searchRow = searchRow;

        _content = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        _chrome = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
            SeparationOverride = 4,
        };
        _chrome.AddChild(searchRow);
        _chrome.AddChild(_content);
        BookRoot.AddChild(_chrome);
    }

    private void ShowList()
    {
        EnsureChrome();
        RefreshList();
    }

    /// <summary>
    /// Daiquiri: refresh only the content area so the search box never loses focus.
    /// </summary>
    private void RefreshList()
    {
        EnsureChrome();
        if (_content == null || _chrome == null)
            return;
        // Daiquiri: search belongs to the list view only.
        if (_searchRow != null)
        {
            if (_searchRow.Parent == null)
                _chrome.AddChild(_searchRow);
            _searchRow.SetPositionInParent(0);
        }
        _content.RemoveAllChildren();

        var scroll = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        var list = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 6,
        };
        scroll.AddChild(list);

        foreach (var book in _books.Where(MatchesFilter).OrderByDescending(b => b.Draft))
        {
            var card = new PanelContainer
            {
                HorizontalExpand = true,
            };
            card.AddStyleClass("BackgroundPanel");
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 6,
                Margin = new Thickness(4),
            };
            row.AddChild(BookWriterCovers.CoverPanel(book.CoverColor, book.CoverDecor, book.CoverIcon));
            var textCol = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            var genreName = Loc.GetString($"book-writer-genre-{book.Genre}");
            var titleBtn = new Button
            {
                Text = book.Draft
                    ? $"{Loc.GetString("book-writer-draft-tag")} {book.Title} ({book.Author}) [{genreName}]"
                    : $"{book.Title} ({book.Author}) [{genreName}]",
                HorizontalExpand = true,
                ClipText = true,
            };
            var id = book.Id;
            var isDraft = book.Draft;
            titleBtn.OnPressed += _ =>
            {
                if (isDraft)
                    OpenDraft(id);
                else
                    ShowBook(id);
            };
            var desc = new Label
            {
                Text = book.Description,
                HorizontalExpand = true,
                ClipText = true,
                ModulateSelfOverride = new Color(0.7f, 0.7f, 0.7f),
            };
            textCol.AddChild(titleBtn);
            textCol.AddChild(desc);
            row.AddChild(textCol);
            card.AddChild(row);
            list.AddChild(card);
        }

        var write = new Button { Text = Loc.GetString("book-writer-new-book"), HorizontalExpand = true };
        write.OnPressed += _ =>
        {
            var win = new BookWriterEditorWindow();
            win.OnSave += (id, title, desc, color, decor, icon, genre, draft, pages) =>
                OnSaveBook?.Invoke(id, title, desc, color, decor, icon, genre, draft, pages);
            win.OpenCentered();
        };
        var drafts = new Button
        {
            Text = Loc.GetString("book-writer-drafts"),
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _draftsOnly,
        };
        drafts.OnToggled += args =>
        {
            _draftsOnly = args.Pressed;
            RefreshList();
        };
        var bottomBar = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 4,
        };
        bottomBar.AddChild(write);
        bottomBar.AddChild(drafts);
        _content.AddChild(scroll);
        _content.AddChild(bottomBar);
    }

    private bool MatchesFilter(BookWriterBookInfo book)
    {
        // Daiquiri: drafts view shows only the viewer's own drafts (server filters).
        if (_draftsOnly && !book.Draft)
            return false;
        if (!string.IsNullOrEmpty(_genreFilter) && book.Genre != _genreFilter)
            return false;
        if (string.IsNullOrWhiteSpace(_search))
            return true;
        var query = _search.Trim();
        return book.Title.Contains(query, StringComparison.OrdinalIgnoreCase)
            || book.Author.Contains(query, StringComparison.OrdinalIgnoreCase)
            || book.Description.Contains(query, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Daiquiri: continue writing a draft (or editing an own book) in the editor window.
    /// </summary>
    private void OpenDraft(string id)
    {
        OpenEditor(id);
    }

    private void OpenEditor(string id)
    {
        var book = _books.FirstOrDefault(b => b.Id == id);
        if (book == null)
            return;
        var win = new BookWriterEditorWindow();
        win.LoadDraft(
            book.Id, book.Title, book.Description,
            book.CoverColor, book.CoverDecor, book.CoverIcon, book.Genre,
            new List<string>(book.Pages));
        win.OnSave += (draftId, title, desc, color, decor, icon, genre, draft, pages) =>
            OnSaveBook?.Invoke(draftId, title, desc, color, decor, icon, genre, draft, pages);
        win.OpenCentered();
    }

    private void ShowBook(string id)
    {
        var book = _books.FirstOrDefault(b => b.Id == id);
        if (book == null || book.Pages.Count == 0)
            return;

        _readId = id;
        _readPage = 0;
        ShowBookPage(book);
    }

    private void ShowBookPage(BookWriterBookInfo book)
    {
        EnsureChrome();
        if (_content == null)
            return;
        // Daiquiri: search out of layout in read view (it rebuilds the list).
        _searchRow?.Orphan();
        _content.RemoveAllChildren();
        _readPage = Math.Clamp(_readPage, 0, book.Pages.Count - 1);

        var head = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 4,
        };
        head.AddChild(BookWriterCovers.CoverPanel(book.CoverColor, book.CoverDecor, book.CoverIcon));
        head.AddChild(new Label
        {
            Text = $"{book.Title} ({book.Author})",
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            ClipText = true,
        });

        var scroll = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        var body = new RichTextLabel { HorizontalExpand = true };
        body.SetMessage(book.Pages[_readPage]);
        scroll.AddChild(body);

        var pages = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };
        var prev = new Button { Text = "◀", Disabled = _readPage <= 0 };
        var counter = new Label
        {
            Text = $"{_readPage + 1} / {book.Pages.Count}",
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
        };
        var next = new Button { Text = "▶", Disabled = _readPage >= book.Pages.Count - 1 };
        prev.OnPressed += _ => { _readPage--; ShowBookPage(book); };
        next.OnPressed += _ => { _readPage++; ShowBookPage(book); };
        pages.AddChild(prev);
        pages.AddChild(counter);
        pages.AddChild(next);

        var bar = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };
        var back = new Button { Text = Loc.GetString("book-writer-back"), HorizontalExpand = true };
        back.OnPressed += _ => ShowList();
        var print = new Button { Text = Loc.GetString("book-writer-print"), HorizontalExpand = true };
        print.OnPressed += _ =>
        {
            // Daiquiri: cooldown warning popup at the cursor.
            if (_printCooldown > 0)
            {
                var popup = new Popup();
                popup.AddChild(new PanelContainer
                {
                    PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(32, 32, 40) },
                    Children =
                    {
                        new Label { Text = Loc.GetString("book-writer-print-cooldown"), Margin = new Thickness(8) },
                    },
                });
                popup.OpenAtMouse();
                Timer.Spawn(2500, () => popup.Orphan());
                return;
            }
            OnPrintBook?.Invoke(_readId);
        };
        var delete = new Button { Text = Loc.GetString("book-writer-delete"), HorizontalExpand = true };
        delete.OnPressed += _ =>
        {
            OnDeleteBook?.Invoke(_readId);
            ShowList();
        };
        bar.AddChild(back);
        bar.AddChild(print);
        var readBook = _books.FirstOrDefault(b => b.Id == _readId);
        if (readBook != null && readBook.Editable)
        {
            var edit = new Button { Text = Loc.GetString("book-writer-edit"), HorizontalExpand = true };
            edit.OnPressed += _ => OpenEditor(_readId);
            bar.AddChild(edit);
        }
        bar.AddChild(delete);

        _content.AddChild(head);
        _content.AddChild(scroll);
        _content.AddChild(pages);
        _content.AddChild(bar);
    }

}
