using System.Numerics;
using System;
using Content.Client.Stylesheets;
using Content.Shared._Starlight.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.IoC;

namespace Content.Client.PDA;

[Virtual]
[GenerateTypedNameReferences]
public partial class PdaWindow : BaseWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;

    private Color _borderBase = Color.White;
    private Action<bool>? _onGlassBool;
    private Action<int>? _onGlassInt;

    public string? BorderColor
    {
        get => Background.ActualModulateSelf.ToHex();

        set
        {
            _borderBase = Color.FromHex(value, Color.White);
            ApplyBorder();
        }
    }

    public string? AccentHColor
    {
        get => AccentH.ActualModulateSelf.ToHex();

        set
        {
            AccentH.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentH.Visible = value != null;
        }
    }

    public string? AccentVColor
    {
        get => AccentV.ActualModulateSelf.ToHex();

        set
        {
            AccentV.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentV.Visible = value != null;
        }
    }

    public PdaWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _onGlassBool = _ => ApplyBorder();
        _onGlassInt = _ => ApplyBorder();
        _cfg.OnValueChanged(StarlightCCVars.UIGlassTheme, _onGlassBool, true);
        _cfg.OnValueChanged(StarlightCCVars.UIGlassTransparency, _onGlassInt);

        CloseButton.OnPressed += _ => Close();
        XamlChildren = ContentsContainer.Children;

        AccentH.Visible = false;
        AccentV.Visible = false;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        if (_onGlassBool != null)
            _cfg.UnsubValueChanged(StarlightCCVars.UIGlassTheme, _onGlassBool);
        if (_onGlassInt != null)
            _cfg.UnsubValueChanged(StarlightCCVars.UIGlassTransparency, _onGlassInt);
    }

    private const float PdaGlassMinAlpha = 0.35f;

    private void ApplyBorder()
    {
        var color = _borderBase;
        if (_cfg.GetCVar(StarlightCCVars.UIGlassTheme))
        {
            var alpha = MathF.Max(PdaGlassMinAlpha, GlassTheme.TransparencyToAlpha(
                _cfg.GetCVar(StarlightCCVars.UIGlassTransparency)));
            color = new Color(color.R, color.G, color.B, color.A * alpha);
        }
        Background.ModulateSelfOverride = color;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}
