using Content.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Input;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Manual lobby music switcher (previous / current track / next) with a rocking vinyl.
/// Replaces the servers hub in the lobby. Wired up by <see cref="LobbyState"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LobbyMusicSwitcher : BoxContainer
{
    private static readonly string[] RockFrames =
    {
        "/Textures/_Starlight/Interface/Vinyl/vinyl_0.png",
        "/Textures/_Starlight/Interface/Vinyl/vinyl_1.png",
        "/Textures/_Starlight/Interface/Vinyl/vinyl_2.png",
        "/Textures/_Starlight/Interface/Vinyl/vinyl_3.png",
        "/Textures/_Starlight/Interface/Vinyl/vinyl_4.png",
        "/Textures/_Starlight/Interface/Vinyl/vinyl_5.png",
    };

    private const int RockMs = 180;

    private int _rockIndex;
    private int _rockDirection = 1;
    private bool _rocking;
    private ContentAudioSystem? _audio;

    /// <summary>
    /// Daiquiri: whether animations should freeze (music paused). Never throws.
    /// </summary>
    private bool AnimPaused()
    {
        try
        {
            _audio ??= IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<ContentAudioSystem>();
        }
        catch
        {
            return false;
        }
        return _audio?.LobbyMusicPaused ?? false;
    }

    public LobbyMusicSwitcher()
    {
        RobustXamlLoader.Load(this);
        VinylRect.OnKeyBindDown += OnVinylInput;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _rocking = true;
        RockTick();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _rocking = false;
    }

    private void RockTick()
    {
        if (!_rocking)
            return;

        // Rocking continues even mid-bounce, but freezes while paused.
        if (!AnimPaused())
        {
            _rockIndex += _rockDirection;
            if (_rockIndex >= RockFrames.Length - 1 || _rockIndex <= 0)
                _rockDirection *= -1;
            VinylRect.TexturePath = RockFrames[_rockIndex];
        }
        Timer.Spawn(RockMs, RockTick);
    }

    private bool _bouncing;

    // Daiquiri: smooth high jump with a second bounce on landing.
    // Clicks are ignored until the whole sequence finishes.
    private static readonly float[] BounceHeights =
    {
        -10f, -24f, -40f, -56f, -70f, -54f, -36f, -18f, 0f, -12f, -4f, 0f,
    };
    private const int BounceMs = 60;

    private void OnVinylInput(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick || _bouncing || AnimPaused())
            return;

        _bouncing = true;
        BounceTick(0);
    }

    private void BounceTick(int step)
    {
        if (!_bouncing)
            return;

        if (step >= BounceHeights.Length)
        {
            VinylRect.Margin = new Thickness(0f);
            _bouncing = false;
            return;
        }
        var h = BounceHeights[step];
        VinylRect.Margin = new Thickness(0f, h, 0f, -h);
        Timer.Spawn(BounceMs, () => BounceTick(step + 1));
    }
}
