using System.Collections.Generic;
using System.Linq;
using Content.Client.Audio;
using Content.Shared.Audio.Events;
using Content.Shared.GameTicking.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Lobby music queue with playlist selector. Left: Queue button + playlist toggles. Right: track list.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LobbyMusicQueueWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private ContentAudioSystem? _audio;
    private readonly Dictionary<string, Button> _playlistButtons = new();
    private readonly Dictionary<string, CheckBox> _trackChecks = new();
    private readonly List<(Button Button, string Filename)> _rows = new();
    private string _selectedView = "Queue";
    private int _buildId;
    private List<string>? _pendingTracks;

    public LobbyMusicQueueWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _audio = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<ContentAudioSystem>();
        _audio.LobbySoundtrackChanged += OnTrackChanged;
        _audio.LobbyPlaylistChanged += OnPlaylistChanged;
        OnOpen += BuildUI;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        OnOpen -= BuildUI;
        if (_audio != null)
        {
            _audio.LobbySoundtrackChanged -= OnTrackChanged;
            _audio.LobbyPlaylistChanged -= OnPlaylistChanged;
        }
    }

    private void OnTrackChanged(LobbySoundtrackChangedEvent ev)
    {
        if (!IsOpen)
            return;
        BuildUI();
    }

    private void OnPlaylistChanged()
    {
        if (!IsOpen)
            return;
        BuildUI();
    }

    private void BuildUI()
    {
        _buildId++;
        TrackList.RemoveAllChildren();
        _rows.Clear();
        _trackChecks.Clear();
        BuildPlaylistButtons();
        var tracks = GetViewTracks(_selectedView);
        _pendingTracks = new List<string>(tracks);
        PumpQueue(_buildId);
    }

    private void BuildPlaylistButtons()
    {
        PlaylistList.RemoveAllChildren();
        _playlistButtons.Clear();

        var queueBtn = new Button
        {
            Text = "Очередь",
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _selectedView == "Queue",
        };
        queueBtn.OnPressed += _ => SelectView("Queue");
        PlaylistList.AddChild(queueBtn);
        _playlistButtons["Queue"] = queueBtn;

        var playlists = _prototypeManager.EnumeratePrototypes<LobbyPlaylistPrototype>()
            .OrderBy(p => p.ID);

        foreach (var playlist in playlists)
        {
            var btn = new Button
            {
                Text = playlist.Name,
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = _selectedView == playlist.ID,
            };
            btn.OnPressed += _ => SelectView(playlist.ID);
            PlaylistList.AddChild(btn);
            _playlistButtons[playlist.ID] = btn;
        }
    }

    private void SelectView(string view)
    {
        _selectedView = view;
        foreach (var (id, btn) in _playlistButtons)
            btn.Pressed = id == view;
        BuildUI();
    }

    private void PumpQueue(int id)
    {
        if (id != _buildId || TrackList.Disposed)
            return;

        var current = _audio?.CurrentLobbyTrack;
        for (var i = 0; i < 8 && _pendingTracks is { Count: > 0 }; i++)
        {
            var filename = _pendingTracks[0];
            _pendingTracks.RemoveAt(0);
            var name = TrackDisplayName(filename);
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            if (_selectedView != "Queue")
            {
                var inPlaylist = IsTrackInPlaylist(filename, _selectedView);
                var check = new CheckBox
                {
                    Pressed = inPlaylist,
                };
                check.OnToggled += args => OnTrackMembershipToggled(filename, args.Pressed);
                row.AddChild(check);
                _trackChecks[filename] = check;
            }

            var button = new Button
            {
                Text = filename == current ? $"▶ {name}" : name,
                HorizontalExpand = true,
                Disabled = filename == current,
            };
            button.OnPressed += _ => _audio?.PlayLobbyTrack(filename);
            row.AddChild(button);
            TrackList.AddChild(row);
            _rows.Add((button, filename));
        }

        if (_pendingTracks is { Count: > 0 })
        {
            Timer.Spawn(30, () => PumpQueue(id));
        }
    }

    private void OnTrackMembershipToggled(string filename, bool pressed)
    {
        if (_audio == null || _selectedView == "Queue")
            return;
        _audio.SetTrackMembership(_selectedView, filename, pressed);
    }

    private bool IsTrackInPlaylist(string filename, string playlistId)
    {
        if (_prototypeManager.TryIndex<LobbyPlaylistPrototype>(playlistId, out var proto))
            return proto.Tracks.Any(t => t.ToString() == filename);
        return false;
    }

    private List<string> GetViewTracks(string view)
    {
        if (view == "Queue")
            return _audio?.LobbyPlaylistTracks?.ToList() ?? new List<string>();

        if (_prototypeManager.TryIndex<LobbyPlaylistPrototype>(view, out var proto))
            return proto.Tracks.Select(t => t.ToString()).ToList();

        return new List<string>();
    }

    private string TrackDisplayName(string filename)
    {
        if (_prototypeManager.TryIndex<LobbyTrackPrototype>(filename, out var proto))
            return proto.Title;
        return filename;
    }
}
