using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared._Starlight.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private IClientConsoleHost _consoleHost = default!;
        [Dependency] private IConfigurationManager _configurationManager = default!;

        private string _serverName = string.Empty;

        // Daiquiri: panel hover fade, 1% per 0.05s down to 95% opacity and back.
        // Fades only the panel's own background: ModulateSelf never reaches children,
        // so inner plaques (e.g. the name/age card) stay crisp. Reads the live
        // stylesheet tint each step, so glass transparency keeps working.
        private readonly Dictionary<PanelContainer, (int Gen, float Factor)> _panelFades = new();
        private const float PanelFadeMin = 0.95f;
        private const float PanelFadeStep = 0.01f;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);

            //Starlight start
            _serverName = _configurationManager.GetCVar(StarlightCCVars.ServerName);
            _configurationManager.OnValueChanged(StarlightCCVars.ServerName, OnServerNameChanged, true);

            ServerName.Text = Loc.GetString("ui-lobby-welcome", ("name", _serverName));
            //Starlight end

        // Daiquiri: fade panel backgrounds while hovering them (works with glass too).
        Timer.Spawn(120, () => PollPanelHover());
        }

        private readonly Dictionary<PanelContainer, float> _panelTargets = new();

        private void PollPanelHover()
        {
            if (Disposed)
                return;
            Timer.Spawn(120, () => PollPanelHover());

            Vector2 mouse;
            try
            {
                mouse = UserInterfaceManager.MousePositionScaled.Position;
            }
            catch
            {
                return;
            }

            foreach (var panel in new[]
                     {
                         LeftSideTop, SongPanel, ButtonsCard, CharacterCard,
                         ServerInfoCard, JobsCard, ChatCard,
                     })
            {
                if (panel.Disposed)
                    continue;
                var hovered = panel.GlobalRect.Contains(mouse);
                var target = hovered ? PanelFadeMin : 1f;
                if (_panelTargets.TryGetValue(panel, out var current) && Math.Abs(current - target) < 0.001f)
                    continue;
                _panelTargets[panel] = target;
                FadePanel(panel, target);
            }
        }

        private void FadePanel(PanelContainer panel, float target)
        {
            if (!_panelFades.TryGetValue(panel, out var state))
                state = (0, 1f);
            state.Gen++;
            _panelFades[panel] = state;
            FadePanelStep(panel, target, state.Gen);
        }

        private void FadePanelStep(PanelContainer panel, float target, int gen)
        {
            if (panel.Disposed)
            {
                _panelFades.Remove(panel);
                return;
            }
            if (!_panelFades.TryGetValue(panel, out var state) || state.Gen != gen)
                return;

            var factor = state.Factor;
            if (Math.Abs(factor - target) < PanelFadeStep / 2f)
            {
                factor = target;
                SetPanelFade(panel, factor);
                _panelFades[panel] = (gen, factor);
                return;
            }

            factor += Math.Sign(target - factor) * PanelFadeStep;
            SetPanelFade(panel, factor);
            _panelFades[panel] = (gen, factor);
            Timer.Spawn(50, () => FadePanelStep(panel, target, gen));
        }

        /// <summary>
        /// Daiquiri: background-only fade for a panel. ModulateSelf never propagates
        /// to children, so text and inner plaques stay crisp. At rest the override
        /// is cleared so the stylesheet (including live glass) rules fully.
        /// </summary>
        private static void SetPanelFade(PanelContainer panel, float factor)
        {
            if (factor >= 1f)
            {
                panel.ModulateSelfOverride = null;
                return;
            }
            var tint = panel.TryGetStyleProperty<Color>(Control.StylePropertyModulateSelf, out var t)
                ? t
                : Color.White;
            panel.ModulateSelfOverride = new Color(tint.R, tint.G, tint.B, tint.A * factor);
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void OnServerNameChanged(string serverName)
        {
            ServerName.Text = Loc.GetString("ui-lobby-welcome", ("name", serverName));
            _serverName = serverName;
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
