using System.Collections.Generic;
using System.Linq;
using Content.Client.Audio;
using Content.Shared.GameTicking.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Lobby music queue with playlist selector. Left: playlists with checkboxes. Right: track list.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LobbyMusicQueueWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private ContentAudioSystem? _audio;
    private readonly Dictionary<string, CheckBox> _playlistChecks = new();
    private readonly List<(Button Button, string Filename)> _rows = new();
    private string _selectedPlaylist = "Lobby";
    private int _buildId;
    private List<string>? _pendingTracks;

    public LobbyMusicQueueWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _audio = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<ContentAudioSystem>();
        _audio.LobbySoundtrackChanged += OnTrackChanged;
        OnOpen += BuildUI;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        OnOpen -= BuildUI;
        if (_audio != null)
            _audio.LobbySoundtrackChanged -= OnTrackChanged;
    }

    private void OnTrackChanged(LobbySoundtrackChangedEvent ev)
    {
        if (!IsOpen)
            return;
        BuildUI();
    }

    private void BuildUI()
    {
        _buildId++;
        BuildPlaylists();
        var tracks = GetPlaylistTracks(_selectedPlaylist);
        _pendingTracks = new List<string>(tracks);
        PumpQueue(_buildId);
    }

    private void BuildPlaylists()
    {
        PlaylistList.RemoveAllChildren();
        _playlistChecks.Clear();

        var playlists = _prototypeManager.EnumeratePrototypes<LobbyPlaylistPrototype>()
            .OrderBy(p => p.ID);

        foreach (var playlist in playlists)
        {
            var check = new CheckBox
            {
                Text = playlist.Name,
                Pressed = IsPlaylistEnabled(playlist.ID),
            };
            check.OnToggled += args => OnPlaylistToggled(playlist.ID, args.Pressed);
            PlaylistList.AddChild(check);
            _playlistChecks[playlist.ID] = check;
        }
    }

    private void OnPlaylistToggled(string playlistId, bool pressed)
    {
        if (_audio == null)
            return;
        if (pressed)
            _audio.DisabledPlaylists.Remove(playlistId);
        else
            _audio.DisabledPlaylists.Add(playlistId);

        _audio.ToggleLobbyPlaylist(playlistId, pressed);
        BuildUI();
    }

    private bool IsPlaylistEnabled(string playlistId)
    {
        return !_audio?.DisabledPlaylists?.Contains(playlistId) ?? true;
    }

    private void PumpQueue(int id)
    {
        if (id != _buildId || TrackList.Disposed)
            return;

        var current = _audio?.CurrentLobbyTrack;
        for (var i = 0; i < 8 && _pendingTracks is { Count: > 0 }; i++)
        {
            var filename = _pendingTracks[0];
            _pendingTracks.RemoveAt(0);
            var name = TrackDisplayName(filename);
            var button = new Button
            {
                Text = filename == current ? $"▶ {name}" : name,
                HorizontalExpand = true,
                Disabled = filename == current,
            };
            button.OnPressed += _ => _audio?.PlayLobbyTrack(filename);
            TrackList.AddChild(button);
            _rows.Add((button, filename));
        }

        if (_pendingTracks is { Count: > 0 })
        {
            Timer.Spawn(30, () => PumpQueue(id));
        }
    }

    private List<string> GetPlaylistTracks(string playlistId)
    {
        if (_prototypeManager.TryIndex<LobbyPlaylistPrototype>(playlistId, out var proto))
            return proto.Tracks.Select(t => t.ToString()).ToList();
        return new List<string>();
    }

    private string TrackDisplayName(string filename)
    {
        if (_prototypeManager.TryIndex<LobbyTrackPrototype>(filename, out var proto))
            return proto.Title;
        return filename;
    }
}
