using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.Audio;
using Content.Shared.Audio.Events;
using Content.Shared.GameTicking.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Lobby music queue with playlist selector. Left: Queue button + playlist toggles. Right: track list.
/// All membership changes are local to this player.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LobbyMusicQueueWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private ContentAudioSystem? _audio;
    private readonly Dictionary<string, Button> _playlistButtons = new();
    private string _selectedView = "Queue";
    private int _buildId;
    private List<string>? _pendingTracks;

    public LobbyMusicQueueWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _audio = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<ContentAudioSystem>();
        _audio.LobbySoundtrackChanged += OnTrackChanged;
        _audio.LobbyPlaylistChanged += OnPlaylistChanged;
        OnOpen += BuildUI;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        OnOpen -= BuildUI;
        if (_audio != null)
        {
            _audio.LobbySoundtrackChanged -= OnTrackChanged;
            _audio.LobbyPlaylistChanged -= OnPlaylistChanged;
        }
    }

    private void OnTrackChanged(LobbySoundtrackChangedEvent ev)
    {
        if (!IsOpen)
            return;
        BuildUI();
    }

    private void OnPlaylistChanged()
    {
        if (!IsOpen)
            return;
        BuildUI();
    }

    private void BuildUI()
    {
        _buildId++;
        TrackList.RemoveAllChildren();
        BuildPlaylistButtons();
        var tracks = GetViewTracks(_selectedView);
        _pendingTracks = new List<string>(tracks);
        PumpQueue(_buildId);
    }

    private void BuildPlaylistButtons()
    {
        PlaylistList.RemoveAllChildren();
        _playlistButtons.Clear();

        var queueBtn = new Button
        {
            Text = "Очередь",
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _selectedView == "Queue",
        };
        queueBtn.OnPressed += _ => SelectView("Queue");
        PlaylistList.AddChild(queueBtn);
        _playlistButtons["Queue"] = queueBtn;

        var playlists = _prototypeManager.EnumeratePrototypes<LobbyPlaylistPrototype>()
            .OrderBy(p => p.ID);

        foreach (var playlist in playlists)
        {
            var btn = new Button
            {
                Text = playlist.Name,
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = _selectedView == playlist.ID,
            };
            btn.OnPressed += _ => SelectView(playlist.ID);
            PlaylistList.AddChild(btn);
            _playlistButtons[playlist.ID] = btn;
        }
    }

    private void SelectView(string view)
    {
        _selectedView = view;
        foreach (var (id, btn) in _playlistButtons)
            btn.Pressed = id == view;
        BuildUI();
    }

    private void PumpQueue(int id)
    {
        if (id != _buildId || TrackList.Disposed)
            return;

        // Daiquiri: select/deselect-all header for playlist views.
        if (_selectedView != "Queue" && _pendingTracks is { Count: > 0 } && TrackList.ChildCount == 0)
        {
            var header = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 4,
            };
            var selectAll = new Button { Text = "Выбрать всё", HorizontalExpand = true };
            selectAll.OnPressed += _ => _audio?.SetPlaylistAll(_selectedView, true);
            var deselectAll = new Button { Text = "Убрать всё", HorizontalExpand = true };
            deselectAll.OnPressed += _ => _audio?.SetPlaylistAll(_selectedView, false);
            header.AddChild(selectAll);
            header.AddChild(deselectAll);
            TrackList.AddChild(header);
        }

        var current = _audio?.CurrentLobbyTrack;
        for (var i = 0; i < 8 && _pendingTracks is { Count: > 0 }; i++)
        {
            var filename = _pendingTracks[0];
            _pendingTracks.RemoveAt(0);

            if (filename == "__empty__")
            {
                var emptyLabel = new Label
                {
                    Text = "Ничего не выбрано",
                    HorizontalExpand = true,
                    VerticalExpand = true,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                };
                TrackList.AddChild(emptyLabel);
                return;
            }

            var name = TrackDisplayName(filename);

            if (_selectedView == "Queue")
            {
                var trackRow = new PanelContainer
                {
                    HorizontalExpand = true,
                    MouseFilter = MouseFilterMode.Stop,
                };
                trackRow.AddChild(new Label
                {
                    Text = filename == current ? $"▶ {name}" : name,
                    HorizontalExpand = true,
                    MouseFilter = MouseFilterMode.Ignore,
                });
                trackRow.OnKeyBindDown += args =>
                {
                    if (args.Function == EngineKeyFunctions.UIClick)
                        OnTrackSelected(filename);
                };
                TrackList.AddChild(trackRow);
                continue;
            }

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var check = new CheckBox
            {
                Pressed = _audio?.IsTrackIncluded(_selectedView, filename) ?? true,
                ToolTip = _audio?.IsTrackIncluded(_selectedView, filename) == true
                    ? "Убрать трек из очереди"
                    : "Добавить трек в очередь",
            };
            check.OnToggled += args => _audio?.SetTrackMembership(_selectedView, filename, args.Pressed);
            row.AddChild(check);

            var button = new Button
            {
                Text = filename == current ? $"▶ {name}" : name,
                HorizontalExpand = true,
                Disabled = filename == current,
            };
            button.OnPressed += _ => OnTrackSelected(filename);
            row.AddChild(button);
            TrackList.AddChild(row);
        }

        if (_pendingTracks is { Count: > 0 })
        {
            Timer.Spawn(30, () => PumpQueue(id));
            return;
        }

        // Daiquiri: clear-queue button at the bottom of the Queue view.
        if (_selectedView == "Queue" && !TrackList.Disposed)
        {
            var clearAll = new Button
            {
                Text = "Убрать всё из очереди",
                HorizontalExpand = true,
            };
            clearAll.OnPressed += _ => _audio?.ClearQueue();
            TrackList.AddChild(clearAll);
        }
    }

    private void OnTrackSelected(string filename)
    {
        if (_audio == null)
            return;

        // Daiquiri: clicking a track auto-includes it locally, then plays it first.
        if (_selectedView != "Queue" && !_audio.IsTrackIncluded(_selectedView, filename))
            _audio.SetTrackMembership(_selectedView, filename, true);

        _audio.PlayLobbyTrackForced(filename);
    }

    private List<string> GetViewTracks(string view)
    {
        if (view == "Queue")
        {
            var tracks = _audio?.LobbyPlaylistTracks?.ToList() ?? new List<string>();
            if (tracks.Count == 0)
                return new List<string> { "__empty__" };
            return tracks;
        }

        if (_prototypeManager.TryIndex<LobbyPlaylistPrototype>(view, out var proto))
            return proto.Tracks.Select(t => t.ToString()).ToList();

        return new List<string>();
    }

    private string TrackDisplayName(string filename)
    {
        if (_prototypeManager.TryIndex<LobbyTrackPrototype>(filename, out var proto))
            return proto.Title;
        return filename;
    }
}
